CREATE DATABASE blogapp;

CREATE TABLE blogs (
  id SERIAL KEY AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  author VARCHAR(100) NOT NULL,
  date DATETIME DEFAULT CURRENT_TIMESTAMP,
  image TEXT NOT NULL
);

ALTER TABLE blogs ADD COLUMN types JSON;
